www:
  container_name: ongo_dev_www
  hostname: ongo_dev_www
  image: alexk7898/ongo:www-develop
  ports:
    - "8083:80"
  restart: always
  links:
    - api:api
  volumes:
    - "./www/dist:/var/www/html"
    - ./logs/www:/var/log
api:
  container_name: ongo_dev_api
  image: alexk7898/ongo:api-develop
  volumes:
    - "./api:/var/www"
    - ./logs/api:/var/log
  external_links:
    - mysql_dev:mysql
    - memcached_dev:memcached
  environment:
    - MYSQL_HOST=dev.ongophotos.com
    - MYSQL_DB=ongo_test
    - MYSQL_USER=root
    - MYSQL_PASSWORD
    - CACHE_TYPE=memcached
    - CACHE_ENDPOINT=memcached
    - SYSLOG_HOSTNAME=ongo_dev_api
vsplunk:
  image: busybox
  volumes:
    - /opt/splunk/etc
    - /opt/splunk/var
splunkforwarder:
  container_name: ongo_dev_splunk
  image: alexk7898/universalforwarder
  volumes_from:
    - vsplunk
  volumes:
    - ./logs/splunkforwarder:/logs
  environment:
    - SPLUNK_START_ARGS=--accept-license --answer-yes --no-prompt
    - SPLUNK_SERVER=192.168.99.100
    - SPLUNK_SERVER_PORT=8088
    - SPLUNK_LOGFILE_PATTERN=/logs/*/*/*.log 
    - SPLUNK_INDEX=main
