ongo-dev-www:
  container_name: ongo_www_dev
  build: www
  ports:
    - "8083:80"
    - "80:80"
  links:
    - ongo-dev-api:api
  volumes:
    - ../www/dist:/var/www/html
ongo-dev-api:
  container_name: ongo_api_dev
  build: api
  ports:
    - "9000:9000"
  volumes:
    - ../api:/var/www
